kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: knoxville
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: knoxville
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
